# Generated by Django 3.1.2 on 2020-11-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutpass', models.CharField(default='', max_length=200)),
                ('apellidos', models.CharField(default='', max_length=200)),
                ('nombres', models.CharField(default='', max_length=200)),
                ('fechanac', models.DateField(default='')),
                ('pais', models.CharField(default='', max_length=200)),
                ('correo', models.EmailField(default='', max_length=200)),
                ('foto', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
