# Generated by Django 3.1.3 on 2020-11-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201107_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agregar',
            old_name='rutpass',
            new_name='rut',
        ),
    ]
