# Generated by Django 3.1.3 on 2020-11-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201107_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agregar',
            old_name='apellidom',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='agregar',
            old_name='fechanac',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='agregar',
            old_name='apellidop',
            new_name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='agregar',
            name='paisorig',
        ),
    ]
